[python]
include_extensions = ["py", "toml"]
exclude_patterns = ["*.pyc", "__pycache__/", ".venv/"]

[cpp]
include_extensions = ["cpp"]
exclude_patterns = ["node_modules/", "dist/", "build/"]

[rust]
include_extensions = ["rs"]
exclude_patterns = ["target/"]
include_file_in_tree = ["Cargo.toml", "Cargo.lock"]
