[python]
extensions = ["py"]
exclude = ["*.pyc", "__pycache__/", ".venv/"]

[cpp]
extensions = ["cpp", "txt"]
exclude = ["node_modules/", "dist/", "build/"]

[rust]
extensions = ["rs"]
exclude = ["target/"]
include_file_in_tree = ["Cargo.toml", "Cargo.lock"]
